chore: Upgrade github.com/cockroachdb/swiss for Go 1.25 support
Go 1.25 incompatibility detected in
* https://github.com/Homebrew/homebrew-core/pull/226636

then:
* reported upstream in https://github.com/cockroachdb/swiss/issues/48
* fixed upstream https://github.com/cockroachdb/swiss/pull/49

This PR brings just this upstream fix upstream to ipfs.
Alternatively we could wait until
* https://github.com/ipfs/kubo/pull/10850

is merged and released an then upgrade the `github.com/ipfs/kubo` direct dependancy.

---

Before:
go1.25rc1 build ./...
github.com/cockroachdb/swiss
# github.com/cockroachdb/swiss
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/map.go:286:7: undefined: hashFn
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/map.go:337:14: undefined: getRuntimeHasher
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/map.go:338:22: undefined: fastrand64
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/map.go:600:23: undefined: fastrand64
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/map.go:649:19: undefined: fastrand64
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/map.go:670:20: undefined: fastrand64
../../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20250327203710-2932b022f6df/options.go:30:14: undefined: hashFn

Upgrade:
go get -u github.com/cockroachdb/swiss && go mod tidy
go: upgraded github.com/cockroachdb/swiss v0.0.0-20250327203710-2932b022f6df => v0.0.0-20250624142022-d6e517c1d961

After:
go1.25rc1 build ./...
(build successful)